autointegrated: false
currentnamespace: kubemq
currentstatefulset: kubemq-cluster
host: 4.246.227.69
grpcport: 50000
restport: 9090
apiport: 8080
issecured: false
certfile: ""
kubeconfigpath: ""
connectiontype: grpc
defaulttoken: ""
clientid: ""
authtokenfile: ""
licensedata: ""
licensekey: ""
